version: '3.8'

services:
  auditforge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auditforge
    ports:
      - "3000:3000"  # Frontend
      - "3001:3001"  # Backend API
    environment:
      - NODE_ENV=production
      - PORT=3001
      - AIML_API_KEY=${AIML_API_KEY}
      - AIML_BASE_URL=https://api.aimlapi.com/v1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
